### ISSUE TITLE
drivers/auxdisplay/openvfd/controllers/fonts/icons_source/*.bmp: 0B?

### ISSUE THREAD

**Issue by 7Ji** [unifreq/linux-6.1.y#14]
openvfd 驱动的图标资源大小均为0，请问是有意为之吗？如果不是的话我开个PR sync一下源驱动的图标资源顺便bump到1.4.2。

**Comment by unifreq** [comment]
内核代码里应该不允许有二进制资源的，在驱动代码里有这个吗？

**Comment by 7Ji** [comment]
https://github.com/arthur-liberman/linux_openvfd/tree/master/driver/controllers/fonts/icons_source
